-- MySQL Script generated by MySQL Workbench
-- Sat Nov 19 14:28:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blooddonationsystemdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blooddonationsystemdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blooddonationsystemdb` DEFAULT CHARACTER SET latin1 ;
USE `blooddonationsystemdb` ;

-- -----------------------------------------------------
-- Table `blooddonationsystemdb`.`tbl_bloodbank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blooddonationsystemdb`.`tbl_bloodbank` (
  `idBloodbank` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBloodbank`),
  UNIQUE INDEX `idBloodbank_UNIQUE` (`idBloodbank` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blooddonationsystemdb`.`tbl_donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blooddonationsystemdb`.`tbl_donor` (
  `idDonor` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `date_of_birth` DATE NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `bloodGroup` VARCHAR(45) NOT NULL,
  `cnp` CHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`idDonor`),
  UNIQUE INDEX `idDonor_UNIQUE` (`idDonor` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blooddonationsystemdb`.`tbl_bloodstock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blooddonationsystemdb`.`tbl_bloodstock` (
  `idBloodBag` INT(11) NOT NULL AUTO_INCREMENT,
  `idBloodBank` INT(11) NOT NULL,
  `bloodGroup` VARCHAR(45) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `expirationDate` DATE NULL DEFAULT NULL,
  `donorId` INT(11) NOT NULL,
  PRIMARY KEY (`idBloodBag`),
  UNIQUE INDEX `idBloodStock_UNIQUE` (`idBloodBag` ASC) VISIBLE,
  INDEX `fk_BloodBank_idx` (`idBloodBank` ASC) VISIBLE,
  INDEX `fk_DonorId_idx` (`donorId` ASC) VISIBLE,
  CONSTRAINT `fk_BloodBank`
    FOREIGN KEY (`idBloodBank`)
    REFERENCES `blooddonationsystemdb`.`tbl_bloodbank` (`idBloodbank`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DonorId`
    FOREIGN KEY (`donorId`)
    REFERENCES `blooddonationsystemdb`.`tbl_donor` (`idDonor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blooddonationsystemdb`.`tbl_seeker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blooddonationsystemdb`.`tbl_seeker` (
  `idSeeker` INT(10) NOT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `date_of_birth` DATE NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `blodGroup` VARCHAR(45) NOT NULL,
  `cnp` CHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`idSeeker`),
  UNIQUE INDEX `idSeeker_UNIQUE` (`idSeeker` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blooddonationsystemdb`.`tbl_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blooddonationsystemdb`.`tbl_request` (
  `idRequest` INT(11) NOT NULL AUTO_INCREMENT,
  `requestDate` DATE NULL DEFAULT NULL,
  `idSeeker` INT(11) NOT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `idBloodBank` INT(11) NOT NULL,
  `Approved` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idRequest`),
  UNIQUE INDEX `idRequest_UNIQUE` (`idRequest` ASC) VISIBLE,
  INDEX `fk_Seeker_idx` (`idSeeker` ASC) VISIBLE,
  INDEX `fk_BloodBank_idx` (`idBloodBank` ASC) VISIBLE,
  INDEX `fk_BloodBank_idx2` (`idBloodBank` ASC) VISIBLE,
  CONSTRAINT `fk_ReqBloodBank`
    FOREIGN KEY (`idBloodBank`)
    REFERENCES `blooddonationsystemdb`.`tbl_bloodbank` (`idBloodbank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seeker`
    FOREIGN KEY (`idSeeker`)
    REFERENCES `blooddonationsystemdb`.`tbl_seeker` (`idSeeker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
